# Generated by Django 5.2.6 on 2025-09-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Socket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socket_id", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("capacity", models.IntegerField(default=10)),
                ("current_load", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["socket_id"],
            },
        ),
        migrations.CreateModel(
            name="SortingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("shift_start", models.TimeField(blank=True, null=True)),
                ("shift_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_id", models.CharField(max_length=50, unique=True)),
                (
                    "clothing_type",
                    models.CharField(
                        choices=[
                            ("shirt", "Shirt"),
                            ("pants", "Pants"),
                            ("dress", "Dress"),
                            ("jacket", "Jacket"),
                            ("underwear", "Underwear"),
                            ("accessories", "Accessories"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Grade A - Excellent"),
                            ("B", "Grade B - Good"),
                            ("C", "Grade C - Fair"),
                            ("D", "Grade D - Poor"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("item_count", models.IntegerField(default=0)),
                ("is_processed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "socket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bags",
                        to="sorting.socket",
                    ),
                ),
                (
                    "sorting_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorted_bags",
                        to="sorting.sortingperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="SortedBag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Store"),
                            ("outlet", "Outlet Store"),
                            ("donation", "Donation Center"),
                            ("recycling", "Recycling Facility"),
                            ("disposal", "Disposal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Shipment"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("final_quality_check", models.BooleanField(default=False)),
                ("packaging_notes", models.TextField(blank=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_bag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorted_bag",
                        to="sorting.bag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
