# Generated by Django 5.2.6 on 2025-09-08 14:11

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#808080", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="sortingperson",
            old_name="employee_id",
            new_name="person_id",
        ),
        migrations.RemoveField(
            model_name="socket",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="socket",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="socket",
            name="current_load",
        ),
        migrations.RemoveField(
            model_name="socket",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sortingperson",
            name="email",
        ),
        migrations.RemoveField(
            model_name="sortingperson",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="sortingperson",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="sortingperson",
            name="shift_end",
        ),
        migrations.RemoveField(
            model_name="sortingperson",
            name="shift_start",
        ),
        migrations.AddField(
            model_name="socket",
            name="socket_color",
            field=colorfield.fields.ColorField(
                default="#010101", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="socket",
            name="socket_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sortingperson",
            name="person_color",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="bag",
            name="clothing_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bags",
                to="sorting.clothingtype",
            ),
        ),
    ]
