# Generated by Django 5.2.6 on 2025-09-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0002_clothingtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingtype",
            name="socket",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sorting.socket",
            ),
            preserve_default=False,
        ),
    ]
