# Generated by Django 5.2.6 on 2025-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0003_clothingtype_socket"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingtype",
            name="parameter",
            field=models.CharField(
                choices=[("Standard", "Standard"), ("Extra", "Extra")],
                default="Standard",
                max_length=10,
            ),
        ),
    ]
