# Generated by Django 5.2.6 on 2025-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0004_clothingtype_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingtype",
            name="parameter",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
