# Generated by Django 5.2.6 on 2025-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0005_alter_clothingtype_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingtype",
            name="parameter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Standard", "Standard"),
                    ("Extra", "Extra"),
                    ("Premium", "Premium"),
                    ("Basic", "Basic"),
                    ("Deluxe", "Deluxe"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
