# Generated by Django 5.2.6 on 2025-09-09 13:22

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0007_alter_clothingtype_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bag",
            name="quality_grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="clothingtype",
            name="parameter",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("Standard", "Standard"), ("Extra", "Extra")],
                max_length=50,
                null=True,
            ),
        ),
    ]
