# Generated by Django 5.2.6 on 2025-09-09 13:36

from django.db import migrations, models
import django.core.validators
from multiselectfield import MultiSelectField


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0008_alter_bag_quality_grade_alter_clothingtype_parameter"),
    ]

    operations = [
        # Add new fields to ClothingType first
        migrations.AddField(
            model_name='clothingtype',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingtype',
            name='bag_source',
            field=models.CharField(max_length=3, choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN'),
            preserve_default=False,
        ),
        # Rename the model
        migrations.RenameModel(
            old_name='ClothingType',
            new_name='BagType',
        ),
        # Rename the field in Bag model
        migrations.RenameField(
            model_name='bag',
            old_name='clothing_type',
            new_name='bag_type',
        ),
    ]
