# Generated by Django 5.2.6 on 2025-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0009_auto_20250909_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="bag",
            name="extra",
            field=models.BooleanField(
                default=False, help_text="True if Extra parameter was selected"
            ),
        ),
    ]
