# Generated by Django 5.2.6 on 2025-09-10 08:52

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0010_add_extra_field_to_bag"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#808080", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bag_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="sorting.bagtype",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("bag_type", "name")},
            },
        ),
        migrations.AddField(
            model_name="bag",
            name="bag_subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bags",
                to="sorting.bagsubtype",
            ),
        ),
    ]
