# Generated by Django 5.2.6 on 2025-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sorting", "0011_add_bagsubtype_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="socket",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
