# Generated by Django 5.2.6 on 2025-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0012_socket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='extra',
            field=models.BooleanField(default=False, help_text='Prawda jeśli wybrano parametr Dodatkowy'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('A', 'Klasa A'), ('B', 'Klasa B'), ('C', 'Klasa C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sortedbag',
            name='destination',
            field=models.CharField(choices=[('retail', 'Sklep Detaliczny'), ('outlet', 'Outlet'), ('donation', 'Centrum Darowizn'), ('recycling', 'Zakład Recyklingu'), ('disposal', 'Utylizacja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedbag',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje na Wysyłkę'), ('shipped', 'Wysłane'), ('delivered', 'Dostarczone'), ('returned', 'Zwrócone')], default='pending', max_length=20),
        ),
    ]
