# Generated by Django 5.2.6 on 2025-09-18 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0013_alter_bag_extra_alter_bag_quality_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocketAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='sorting.socket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'socket__socket_id'],
                'unique_together': {('user', 'socket')},
            },
        ),
    ]
