# Generated by Django 5.2.6 on 2025-09-18 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0014_usersocketaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accessible_sockets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSocketAccess',
        ),
    ]
