# Generated by Django 5.2.6 on 2025-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0015_socket_users_delete_usersocketaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='auto_processed_by_next_bag',
            field=models.BooleanField(default=False, help_text='True if automatically processed by next bag'),
        ),
        migrations.AddField(
            model_name='bag',
            name='bag_source',
            field=models.CharField(blank=True, help_text='IN or OUT for SEP socket', max_length=3),
        ),
        migrations.AddField(
            model_name='bag',
            name='processing_time_seconds',
            field=models.IntegerField(blank=True, help_text='Time spent in separator (seconds)', null=True),
        ),
    ]
