# Generated by Django 5.2.6 on 2025-09-19 08:55

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0016_bag_auto_processed_by_next_bag_bag_bag_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', colorfield.fields.ColorField(default='#87CEEB', help_text='Background color for this category', image_field=None, max_length=25, samples=None)),
                ('icon', models.CharField(default='fas fa-layer-group', help_text="FontAwesome icon class (e.g., 'fas fa-tshirt')", max_length=50)),
                ('order', models.IntegerField(default=1, help_text='Display order (lower numbers appear first)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bag Type Category',
                'verbose_name_plural': 'Bag Type Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='bagsubtype',
            name='color',
            field=colorfield.fields.ColorField(default='#808080', help_text='Individual color (overrides category color if set)', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='bagsubtype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for organizing this subtype', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='sorting.bagtypecategory'),
        ),
    ]
