# Generated by Django 5.2.6 on 2025-09-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0017_add_bagtype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagsubtype',
            name='color',
        ),
    ]
