# Generated by Django 5.2.6 on 2025-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0018_remove_bagsubtype_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagsubtype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='bagsubtype',
            name='order',
        ),
    ]
